//! Generated by cot CLI 0.3.0 on 2025-05-19 23:47:26+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "demo-app-cups-manager";
    const MIGRATION_NAME: &'static str = "m_0001_initial";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[
        ::cot::db::migrations::MigrationDependency::model(
            <cot::auth::db::DatabaseUser as ::cot::db::Model>::APP_NAME,
            <cot::auth::db::DatabaseUser as ::cot::db::Model>::TABLE_NAME,
        ),
    ];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] = &[
        ::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("demo_app_cups_manager__cup"))
            .fields(
                &[
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("id"),
                            <cot::db::Auto<i32> as ::cot::db::DatabaseField>::TYPE,
                        )
                        .auto()
                        .primary_key()
                        .set_null(
                            <cot::db::Auto<i32> as ::cot::db::DatabaseField>::NULLABLE,
                        ),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("owner"),
                            <cot::db::ForeignKey<
                                cot::auth::db::DatabaseUser,
                            > as ::cot::db::DatabaseField>::TYPE,
                        )
                        .foreign_key(
                            <cot::auth::db::DatabaseUser as ::cot::db::Model>::TABLE_NAME,
                            <cot::auth::db::DatabaseUser as ::cot::db::Model>::PRIMARY_KEY_NAME,
                            ::cot::db::ForeignKeyOnDeletePolicy::Restrict,
                            ::cot::db::ForeignKeyOnUpdatePolicy::Restrict,
                        )
                        .set_null(
                            <cot::db::ForeignKey<
                                cot::auth::db::DatabaseUser,
                            > as ::cot::db::DatabaseField>::NULLABLE,
                        ),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("name"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("active"),
                            <bool as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<bool as ::cot::db::DatabaseField>::NULLABLE),
                ],
            )
            .build(),
    ];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _Cup {
    #[model(primary_key)]
    pub id: cot::db::Auto<i32>,
    pub owner: cot::db::ForeignKey<cot::auth::db::DatabaseUser>,
    pub name: String,
    pub active: bool,
}
