//! List of migrations for the current app.
//!
//! Generated by cot CLI 0.3.0 on 2025-05-19 23:47:26+00:00

/// The list of migrations for current app.
pub const MIGRATIONS: &[&::cot::db::migrations::SyncDynMigration] = &[];
